#!/bin/bash

# Function to detect OS type and generate correct date command
get_os_type() {
  if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    echo "linux"
  elif [[ "$OSTYPE" == "darwin"* ]]; then
    echo "macos"
  else
    echo "Unsupported OS"
    exit 1
  fi
}

# Function to fetch clip for a single stream
function fetchclip() {
    stream_name=$1
    n=$2

    # Get current timestamp in UTC
    current_time=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

    # Detect OS and calculate start timestamp
    os_type=$(get_os_type)

    if [[ "$os_type" == "linux" ]]; then
        # Linux command to subtract minutes
        start_time=$(date -u -d "$n minutes ago" +"%Y-%m-%dT%H:%M:%SZ")
        output_file="/home/ANT.AMAZON.COM/$USER/Downloads/$stream_name.mp4"
    elif [[ "$os_type" == "macos" ]]; then
        # macOS command to subtract minutes
        start_time=$(date -u -v-"$n"M +"%Y-%m-%dT%H:%M:%SZ")
        output_file="/Users/$USER/Downloads/$stream_name.mp4"
    fi

    # Get data endpoint
    data_endpoint=$(aws kinesisvideo get-data-endpoint --stream-name "$stream_name" --api-name GET_CLIP --output text)

    # Get video clip using the autogenerated timestamps
    aws kinesis-video-archived-media get-clip \
        --endpoint "$data_endpoint" \
        --stream-name "$stream_name" \
        --clip-fragment-selector "FragmentSelectorType=PRODUCER_TIMESTAMP,TimestampRange={StartTimestamp=$start_time,EndTimestamp=$current_time}" \
        "$output_file"

    echo "Clip fetched for stream $stream_name"
}

# Function to fetch clips for a list of streams based on an identifier
function batch_fetchclip() {
    station=$1  # String argument (identifier)
    n=$2  # Second argument (minutes)

    # Define lists of stream names based on the identifier
    if [[ "$station" == "0205" ]]; then
        stream_names=("Atlas-Lab-0205-conveyor_1" "Atlas-Lab-0205-conveyor_2" "Atlas-Lab-0205-conveyor_3" "Atlas-Lab-0205-transfer_1" "Atlas-Lab-0205-transfer_2" "Atlas-Lab-0205-transfer_3")
    elif [[ "$station" == "0206" ]]; then
	    stream_names=("Atlas-Lab-0206-buffer" "Atlas-Lab-0206-reorient" "Atlas-Lab-0206-stow_pod_bx" "Atlas-Lab-0206-stow_pod_iso" "Atlas-Lab-0206-stow_pod_right" "Atlas-Lab-0205-transfer_1" "Atlas-Lab-0205-conveyor_1")
    elif [[ "$station" == "0207" ]]; then
        stream_names=("Atlas-Lab-0207-buffer" "Atlas-Lab-0207-reorient" "Atlas-Lab-0207-stow_pod_bx" "Atlas-Lab-0207-stow_pod_iso" "Atlas-Lab-0207-stow_pod_right" "Atlas-Lab-0205-transfer_2" "Atlas-Lab-0205-conveyor_2")
    elif [[ "$station" == "0208" ]]; then
        stream_names=("Atlas-Lab-0208-buffer" "Atlas-Lab-0208-reorient" "Atlas-Lab-0208-stow_pod_bx" "Atlas-Lab-0208-stow_pod_iso" "Atlas-Lab-0208-stow_pod_right" "Atlas-Lab-0205-transfer_3" "Atlas-Lab-0205-conveyor_3")
    elif [[ "$station" == "0203" ]]; then
        stream_names=("Atlas-Lab-0203-buffer" "Atlas-Lab-0203-reorient" "Atlas-Lab-0203-stow_pod_bx" "Atlas-Lab-0203-stow_pod_iso" "Atlas-Lab-0203-stow_pod_right")
    elif [[ "$station" == "2406" ]]; then
        stream_names=("GEG1-paKivaA02-2406-conveyor_1" "GEG1-paKivaA02-2406-conveyor_2" "GEG1-paKivaA02-2406-conveyor_3" "GEG1-paKivaA02-2406-transfer_1" "GEG1-paKivaA02-2406-transfer_2" "GEG1-paKivaA02-2406-transfer_3")
    elif [[ "$station" == "2408" ]]; then
	    stream_names=("GEG1-paKivaA02-2408-buffer" "GEG1-paKivaA02-2408-reorient" "GEG1-paKivaA02-2408-stow_pod_bx" "GEG1-paKivaA02-2408-stow_pod_iso" "GEG1-paKivaA02-2408-stow_pod_right" "GEG1-paKivaA02-2406-transfer_1" "GEG1-paKivaA02-2406-conveyor_1")
    elif [[ "$station" == "2410" ]]; then
	    stream_names=("GEG1-paKivaA02-2410-buffer" "GEG1-paKivaA02-2410-reorient" "GEG1-paKivaA02-2410-stow_pod_bx" "GEG1-paKivaA02-2410-stow_pod_iso" "GEG1-paKivaA02-2410-stow_pod_right" "GEG1-paKivaA02-2406-transfer_2" "GEG1-paKivaA02-2406-conveyor_2")
    elif [[ "$station" == "2412" ]]; then
	    stream_names=("GEG1-paKivaA02-2412-buffer" "GEG1-paKivaA02-2412-reorient" "GEG1-paKivaA02-2412-stow_pod_bx" "GEG1-paKivaA02-2412-stow_pod_iso" "GEG1-paKivaA02-2412-stow_pod_right" "GEG1-paKivaA02-2406-transfer_3" "GEG1-paKivaA02-2406-conveyor_3")
    else
        echo "Unknown station: $station"
        return 1
    fi

    # Call fetchclip for each stream name in the list
    for stream_name in "${stream_names[@]}"; do
        echo "Fetching clip for $stream_name..."
        fetchclip "$stream_name" "$n"
    done
}

# Main logic to determine which function to call
if [[ "$1" == "batch" ]]; then
    # If the first argument is 'batch', call batch_fetchclip
    batch_fetchclip "$2" "$3"
else
    # Otherwise, assume it's a single fetch and call fetchclip
    fetchclip "$1" "$2"
fi
